//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by taika.rc
//
#define IDS_STRNAME                     1
#define IDD_TAIKA_DIALOG                102
#define IDD_RAPORTIT_PROPPAGE           107
#define IDD_SAAPUNEET_PROPPAGE          108
#define IDR_MAINFRAME                   128
#define IDD_DLGIPEEDIT                  129
#define IDD_DLGIPEDTP                   130
#define IDD_DLGIPECOMBO                 133
#define IDB_ARROWLEFT                   137
#define IDB_ARROWRIGHT                  138
#define IDR_MAINMENU                    139
#define IDR_RAPORTIT_MENU               139
#define IDD_DLGIPECOMBO2                140
#define IDD_DLGUUSIRAPORTTI             141
#define IDD_DLGPARSE                    142
#define IDD_ASETUKSET_PROPP             143
#define IDD_DLGVALITSEASIAKAS           144
#define IDD_DLGLASKUTA                  145
#define IDD_LISTAT_PROPP                146
#define IDR_LISTAT_MENU                 147
#define IDR_ASETUKSET_MENU              148
#define IDD_DLGSIIRRAASIAKKAAT          151
#define IDD_DLGSAVE                     152
#define IDR_ALKAEN                      155
#define IDR_PAATTYEN                    156
#define IDD_DLGSAVELISTAT               158
#define IDB_FOLDER                      159
#define IDD_TYOMATKAT_PROPP             159
#define IDR_TYOMATKAT_MENU              161
#define IDD_DLGVARMUUSKOPIOINTI         162
#define IDD_DLGSIIVOATIETOKANTA         163
#define IDD_DLGPAIVITA                  165
#define IDD_DLGSMTP                     167
#define IDD_DLGERITTELY                 168
#define IDR_LASKUTA                     170
#define IDR_ERITTELY                    171
#define IDR_ERITTELY_TM                 173
#define IDR_ACCKEYS                     175
#define IDD_DLGSAVE2                    176
#define IDI_KELLO                       177
#define IDI_EURO                        178
#define IDB_BMPBINOCULAR                180
#define IDD_DLGETSI                     181
#define IDD_DLGUUSIVANHA                182
#define IDB_BMPINFO                     183
#define IDD_DIALOG1                     184
#define IDD_DLGINFO                     184
#define IDB_BMPPAGE                     185
#define IDB_BMPSULJE                    186
#define IDB_BMPCALENDAR                 187
#define IDI_ASC                         188
#define IDI_DESC                        190
#define IDB_BMPASC                      191
#define IDB_BMPDESC                     192
#define IDD_DLGASETUKSET                193
#define IDD_DLGLUOUUSITIETOKANTA        194
#define IDD_DLGIMPORT                   195
#define IDB_BMPCHECKED                  197
#define IDB_BMPUNCHECKED                198
#define IDD_DIALOG2                     200
#define IDD_DLGMOVING                   200
#define IDI_WORK                        201
#define IDI_CLIENT                      202
#define IDI_TRAVEL                      203
#define IDI_CASH                        204
#define IDB_TAIKA                       206
#define IDB_ENPORIA                     207
#define IDD_ABOUT                       208
#define IDI_EDIT                        209
#define IDD_DLGUUSITYOMATKA             210
#define IDD_DLGUUSIASIAKAS              211
#define IDD_DLGUUSITUOTE                212
#define IDD_DLGUUSILASKUTTAJA           213
#define IDD_DIALOG3                     214
#define IDD_DLGUUSITYOTYYPPI            214
#define IDS_PJNSMTP_UNEXPECTED_SMTP_LOGIN_RESPONSE 512
#define IDS_PJNSMTP_UNEXPECTED_EHLO_RESPONSE 516
#define IDS_PJNSMTP_UNEXPECTED_HELO_RESPONSE 517
#define IDS_PJNSMTP_UNEXPECTED_QUIT_RESPONSE 518
#define IDS_PJNSMTP_UNEXPECTED_MAIL_FROM_RESPONSE 519
#define IDS_PJNSMTP_UNEXPECTED_DATA_RESPONSE 520
#define IDS_PJNSMTP_UNEXPECTED_END_OF_MESSAGE_RESPONSE 521
#define IDS_PJNSMTP_FILE_SIZE_TO_SEND_TOO_LARGE 522
#define IDS_PJNSMTP_CANNOT_SEND_ZERO_BYTE_MESSAGE 523
#define IDS_PJNSMTP_UNEXPECTED_RCPT_TO_RESPONSE 524
#define IDS_PJNSMTP_UNEXPECTED_AUTH_LOGIN_RESPONSE 525
#define IDS_PJNSMTP_UNEXPECTED_AUTH_LOGIN_USERNAME_REQUEST 526
#define IDS_PJNSMTP_UNEXPECTED_AUTH_LOGIN_USERNAME_RESPONSE 527
#define IDS_PJNSMTP_UNEXPECTED_AUTH_LOGIN_PASSWORD_REQUEST 528
#define IDS_PJNSMTP_UNEXPECTED_AUTH_LOGIN_PASSWORD_RESPONSE 529
#define IDS_PJNSMTP_UNEXPECTED_AUTH_PLAIN_RESPONSE 530
#define IDS_STRVERSION                  531
#define IDS_PJNSMTP_UNEXPECTED_AUTH_CRAM_MD5_RESPONSE 535
#define IDS_PJNSMTP_UNEXPECTED_CRAMD_MD5_DIGEST_RESPONSE 536
#define IDS_PJNSMTP_FAILED_NTLM_AUTHENTICATION 537
#define IDS_PJNSMTP_UNEXPECTED_AUTH_NTLM_RESPONSE 538
#define IDS_PJNSMTP_FAIL_BASE64_DECODE  539
#define IDS_PJNSMTP_FAIL_BASE64_ENCODE  540
#define IDS_PJNSMTP_FAIL_CREATE_SSL_SOCKET 541
#define IDS_PJNSMTP_FAIL_CONNECT_SOCKS4_VIASSL 542
#define IDS_PJNSMTP_FAIL_CONNECT_SOCKS5_VIASSL 543
#define IDS_PJNSMTP_FAIL_CONNECT_HTTPPROXY_VIASSL 544
#define IDS_PJNSMTP_FAIL_CONNECT_VIASSL 545
#define IDS_PJNSMTP_FAIL_SEND_VIASSL    546
#define IDS_PJNSMTP_FAIL_RECEIVE_VIASSL 547
#define IDS_PJNSMTP_GRACEFUL_DISCONNECT 548
#define IDS_PJNSMTP_FAIL_QP_ENCODE      549
#define IDS_PJNSMTP_FAIL_Q_ENCODE       550
#define IDC_SHEET_PLACEHOLDER           1002
#define IDC_LSTRAPORTTI                 1003
#define IDC_LSTASIAKASRYHMA             1004
#define IDC_LSTASIAKAS                  1005
#define IDC_CMBTYOTYYPPI                1006
#define IDC_CMBTYONTEKIJA               1007
#define IDC_DTPALKAEN                   1008
#define IDC_DTPPAATTYEN                 1009
#define IDC_LSTSAAPUNEET                1011
#define IDC_LSTTYOT                     1012
#define IDC_LSTMYYNTI                   1012
#define IDC_LSTMATKA                    1013
#define IDC_BTNHYVAKSY                  1015
#define IDC_LSTTYOAJAT                  1017
#define IDC_LSTMYYNNIT                  1018
#define IDC_EDTONE                      1019
#define IDC_EDTTYONTEKIJA               1020
#define IDC_STCLASKUTTAJA               1021
#define IDC_STCPAIVAYS                  1022
#define IDC_DTPDATE                     1023
#define IDC_DTPTIME                     1024
#define IDC_BTNHYVAKSYTTYIHIN           1025
#define IDC_STCASIAKAS                  1026
#define IDC_STCMYYNTI                   1027
#define IDC_STCTYOMATKA                 1028
#define IDC_STCTYOAIKA                  1029
#define IDC_CMBONE                      1031
#define IDC_BTNSAAPUNEISIIN             1032
#define IDC_RADLASKUTETUT               1034
#define IDC_RADLASKUTETUT2              1035
#define IDC_RADLASKUTETUT3              1036
#define IDC_LSTTYOTYYPPI                1037
#define IDC_LSTTYONTEKIJA               1038
#define IDC_CHKASIAKKAAT                1039
#define IDC_CHKASIAKASRYHMAT            1040
#define IDC_CHKTYOTYYPIT                1041
#define IDC_CHKTYONTEKIJAT              1042
#define PIC_QUESTION                    1044
#define IDC_CMBTYYPPI                   1045
#define IDC_STCQUESTION                 1047
#define IDC_CHKPARSE                    1048
#define IDC_STCINFO                     1053
#define IDC_BTNLISAA                    1054
#define IDC_STCEDISTYS                  1055
#define IDC_LSTTIEDOSTOT                1056
#define IDC_RADLASKOHJ1                 1058
#define IDC_RADLASKOHJ2                 1059
#define IDC_RADLASKOHJ3                 1060
#define IDC_STCLASKOHJ                  1061
#define IDC_CMBLASKYRITYS               1062
#define IDC_RDLASKUTUS1                 1063
#define IDC_RDLASKUTUS2                 1064
#define IDC_LSTASIAKKAAT                1064
#define IDC_RDLASKUTUS3                 1065
#define IDC_EDTETSI                     1065
#define IDC_BTNSEURAAVA                 1066
#define IDC_BTNLASKKAIKKI               1068
#define IDC_BTNLASKVALITTU              1069
#define IDC_BTNERITTELY                 1070
#define IDC_CHKKAYNTIKERTA              1071
#define IDC_CMBTILI                     1072
#define IDC_CMBHINNAT                   1073
#define IDC_DTPERAPAIVA                 1074
#define IDC_CMBTILA                     1075
#define IDC_EDTMAKSUAIKA                1076
#define IDC_LSTASIAKASRYHMAT            1078
#define IDC_BTNLIS_RYHMA                1079
#define IDC_BTNPOIS_RYHMA               1080
#define IDC_BTNLIS_ASIAKAS              1081
#define IDC_BTNPOIS_ASIAKAS             1082
#define IDC_BTN_SIIRRA                  1084
#define IDC_BTNSIIRRA                   1087
#define IDC_CMBMODE                     1091
#define IDC_CMBLASKUTTAJA               1092
#define IDC_CMB_LASKUTTAJA              1093
#define IDC_CMBYKSIKKO                  1093
#define IDC_BTNLISAAUUSI                1094
#define IDC_BTNPOISTAVALITUT            1095
#define IDC_BTNLASKUTAVALITUT           1096
#define IDC_BTNLASKUTANAYTETYT          1097
#define IDC_BTNLASKUTAASIAKAS           1098
#define IDC_LSTLASKUTTAJAT              1099
#define IDC_STCAJAT                     1101
#define IDC_CMBAIKA                     1102
#define IDC_BTNLIS_LASKUTTAJA           1103
#define IDC_BTNLISAA_1                  1103
#define IDC_BTNPOIS_LASKUTTAJA          1104
#define IDC_BTNPOISTA_1                 1104
#define IDC_LSTTYOTYYPIT                1105
#define IDC_BTNLIS_TYOTYYPPI            1106
#define IDC_BTNLISAA_2                  1106
#define IDC_BTNPOIS_TYOTYYPPI           1107
#define IDC_BTNPOISTA_2                 1107
#define IDC_SPNASIAKASRYHMAT            1108
#define IDC_SPNASIAKKAAT                1109
#define IDC_SPNTYOTYYPIT                1110
#define IDC_SPN_2                       1110
#define IDC_STCDBNAME                   1111
#define IDC_SPN_1                       1111
#define IDC_CMBASIAKASRYHMA             1112
#define IDC_CMBASIAKAS                  1113
#define IDC_BTNALKAEN                   1116
#define IDC_BTNPAATTYEN                 1117
#define IDC_CHKLASKUTTAJAT              1121
#define IDC_STCTIEDOSTO                 1125
#define IDC_EDTPOLKU                    1126
#define IDC_BTNPOLKU                    1127
#define IDC_LSTTYOMATKAT                1128
#define IDC_LSTTYONTEKIJAT              1130
#define IDC_STCYKSITYIS                 1139
#define IDC_STCTYO                      1140
#define IDC_STCYHTEENSA                 1140
#define IDC_STCEUROA                    1142
#define IDC_EDTKMKERROIN                1143
#define IDC_EDTFILENAME                 1145
#define IDC_EDTPATH                     1146
#define IDC_CHKPOISTA                   1147
#define IDC_RADKOPIOI1                  1148
#define IDC_RADKOPIOI2                  1149
#define IDC_RADKOPIOI3                  1150
#define IDC_BTNVARMUUSKOPIOI            1151
#define IDC_CHKMATKA                    1153
#define IDC_STCVKOPIOITAVA              1154
#define IDC_CHKTYOMATKAT                1158
#define IDC_BTNPOISTA                   1164
#define IDC_CHKLASKUTTAMATTOMAT         1166
#define IDC_CHKLASKUTTAMATTOMATTYOAJAT  1166
#define IDC_CHKLASKUTETUT               1167
#define IDC_CHKLASKUTETUTTYOAJAT        1167
#define IDC_STCVANHAT                   1172
#define IDC_STCUUDET                    1173
#define IDC_PIC                         1174
#define IDC_YES                         1176
#define IDC_YESTOALL                    1177
#define IDC_NOT                         1178
#define IDC_NOTOALL                     1179
#define IDC_EDTSUBJECT                  1183
#define IDC_EDTFROM                     1184
#define IDC_EDTRECIPIENTS               1186
#define IDC_CMB2                        1190
#define IDC_CMB3                        1191
#define IDC_CMB4                        1192
#define IDC_CMB1                        1193
#define IDC_BTNTULOSTA                  1194
#define IDC_CMB5                        1196
#define IDC_BTNLASKUTA                  1197
#define IDC_RADLAHDE1                   1198
#define IDC_RADLAHDE2                   1199
#define IDC_EDTATTACHMENT               1203
#define IDC_CHKSIVUTUS                  1204
#define IDC_EDTYLATUNNISTE              1205
#define IDC_CHKYLATUNNISTE              1206
#define IDC_EDTALATUNNISTE              1207
#define IDC_CHKALATUNNISTE              1208
#define IDC_CHKYLAPAIVAYS               1209
#define IDC_CMBFONTINKOKO               1211
#define IDC_CHKYHTEENVETO               1213
#define IDC_CMBFONTTI                   1214
#define IDC_CHKKMKORVAUS                1215
#define IDC_BTNLAHETA                   1217
#define IDC_EDTPORT                     1218
#define IDC_EDTPASSWORD                 1219
#define IDC_CHKKAYTAAUTH                1220
#define IDC_EDTUSERNAME                 1221
#define IDC_CHKMUISTAUN                 1222
#define IDC_CMBSMTPSERVER               1223
#define IDC_STCLIITE                    1225
#define IDC_CMB_LASKUTTAJA_TM           1226
#define IDC_BTNETSI                     1227
#define IDC_STCICON                     1234
#define IDC_BTNASIAKASRYHMA             1235
#define IDC_BTNASIAKAS                  1236
#define IDC_BTNLASKUTTAJA               1237
#define IDC_BTNTYOTYYPPI                1238
#define IDC_CMBNAYTA                    1240
#define IDC_STCVALITUT                  1241
#define IDC_BTNVALMORE                  1242
#define IDC_BTNYHTMORE                  1243
#define IDC_LSTLISTA                    1244
#define IDC_STCSULJE                    1248
#define IDC_CHKTUOTERYMAT               1250
#define IDC_TAB                         1252
#define IDC_LSTTUOTERYHMAT              1258
#define IDC_LSTTUOTTEET                 1259
#define IDC_CHKTUOTTEET                 1260
#define IDC_STCATTACHMENT               1274
#define IDC_STCTYPE                     1275
#define IDC_STCOPT1                     1276
#define IDC_STCOPT2                     1277
#define IDC_TABMAIN                     1277
#define IDC_STCOPT3                     1278
#define IDC_STCSEP1                     1278
#define IDC_STCOPT4                     1279
#define IDC_STCSEP2                     1279
#define IDC_STCOPT5                     1280
#define IDC_STCSEP3                     1280
#define IDC_STCSEP4                     1281
#define IDC_STCSEP5                     1282
#define IDC_CHKLASKUTTAMATTOMATMYYNNIT  1284
#define IDC_CHKLASKUTETUTMYYNNIT        1285
#define IDC_STCOPT6                     1287
#define IDC_BTNFOLDER                   1287
#define IDC_STCOPT7                     1288
#define IDC_STCPATHNAME                 1288
#define IDC_LSTONE                      1291
#define IDC_STCYRITYS                   1293
#define IDC_STCREPORT                   1295
#define IDC_STCSULJE2                   1296
#define IDC_CHKYHDISTATAPAHTUMAT        1298
#define IDC_CHECK1                      1299
#define IDC_COMBO1                      1300
#define IDC_CMBYHTEENVETO               1300
#define IDC_EDTABOUT                    1301
#define IDC_EDTALOITUSAIKA              1302
#define IDC_EDTLOPETUSAIKA              1303
#define IDC_EDTMAARA                    1304
#define IDC_EDTMYYNTIHINTA              1305
#define IDC_EDTKOKONAISHINTA            1306
#define IDC_EDTALVPROSENTTI             1307
#define IDC_STCMAARA                    1308
#define IDC_EDTSTARTMETER               1309
#define IDC_EDTENDMETER                 1310
#define IDC_EDTPRIVATE                  1311
#define IDC_EDTSTARTTIME                1312
#define IDC_EDTENDTIME                  1313
#define IDC_EDTSTARTPLACE               1314
#define IDC_EDTENDPLACE                 1315
#define IDC_EDTPURPOSE                  1316
#define IDC_CMBWORKER                   1317
#define IDC_CMBBILLER                   1318
#define IDC_RDCHARGED1                  1318
#define IDC_RDCHARGED2                  1319
#define IDC_RDNAYTA1                    1319
#define IDC_RDNAYTA2                    1320
#define IDC_EDTNAME                     1320
#define IDC_EDTADDRESS                  1321
#define IDC_EDTNOTE                     1322
#define IDC_EDTSHORTNOTE                1323
#define IDC_EDTINFO                     1324
#define IDC_EDTCUSTOMERNUMBER           1325
#define IDC_EDTPRODUCTNUMBER            1326
#define IDC_CMBUNIT                     1327
#define IDC_EDTPURCHASEPRICE            1328
#define IDC_EDTSELLPRICE                1329
#define IDC_EDTALV                      1330
#define IDC_EDTEMAIL                    1331
#define IDC_STATIC5                     1332
#define IDC_STATIC2                     1333
#define IDC_STATIC3                     1334
#define IDC_STATIC4                     1335
#define IDC_STATIC6                     1336
#define IDC_STATIC1                     1337
#define IDC_STATIC7                     1338
#define IDC_STATIC8                     1340
#define IDC_STATIC9                     1341
#define IDC_STATIC10                    1342
#define IDC_STATIC13                    1343
#define IDC_STATIC11                    1343
#define IDM_LOPETA                      32771
#define ID_TIEDOSTO_LOPETA              32779
#define IDM_AVAA_RAPORTTI               32786
#define IDM_TALLETA_KAIKKI_RAPORTIT     32787
#define IDM_TALLETA_RAPORTTI            32791
#define IDM_TALLETA_LISTAT              32793
#define IDM_AVAA_LISTAT                 32794
#define IDM_PU_VANHIN_TYO               32796
#define IDM_PU_VIIMEKSI_ASETETTU        32797
#define IDM_PU_NYKYINEN_PVM             32798
#define IDM_PU_NYKYINEN_M1              32799
#define IDM_PU_NYKYINEN_M2              32800
#define IDM_PU_NYKYINEN_M3              32801
#define IDM_PU_UUSIN_TYO                32804
#define IDM_VARMUUSKOPIOI_TIETOKANTA    32806
#define IDM_VAIHDA_TIETOKANTA           32807
#define IDM_AVAA_RAPORTTI_TM            32808
#define IDM_TALLETA_RAPORTTI_TM         32809
#define IDM_SIIVOA_TIETOKANTA           32811
#define IDM_NAYTETYT                    32812
#define IDM_VALITUT                     32813
#define IDM_ASIAKKAAT                   32814
#define IDM_NAYTETYT_TYOT               32815
#define IDM_VALITUT_TYOT                32816
#define IDM_VALITUT_ASIAKAS_TYOT        32817
#define IDM_NAYTETYT_TYOAJAT            32818
#define IDM_VALITUT_TYOAJAT             32819
#define IDM_VALITUT_TYONTEKIJA_TYOAJAT  32820
#define IDM_EMAIL                       32821
#define IDM_VALITUT_TYOMATKAT           32825
#define IDM_NAYTETYT_TYOMATKAT          32826
#define IDM_VALITUN_TYOMATKAT           32827
#define IDK_VALITSEKAIKKI               32828
#define IDK_AVAA                        32829
#define IDK_TALLETA                     32830
#define IDK_ETSI                        32831
#define IDK_UUSI                        32832
#define IDK_ETSI_F3                     -32703
#define IDK_POISTA_DEL                  32834
#define IDK_POISTA_X                    32835
#define IDM_ASETUKSET                   32836
#define IDM_LUO_UUSI_TIETOKANTA         32837
#define IDM_TUO_LASKUTUSOHJELMASTA      32838
#define IDK_IMPORT                      32839
#define IDK_PAIVITA_V5                  32840
#define ID_ACCELERATOR32841             32841
#define IDK_EMAIL                       32841
#define ID_TIETOJA_T                    32843
#define ID_TIETOJA_T32844               32844
#define ID_TIETOJA_T32845               32845
#define IDM_ABOUT                       32846

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1344
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
